SurveyManager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls', namespace='base'))
]

base/urls.py
from django.urls import path
from . import views

app_name = 'base'

urlpatterns = [
    path('', views.list, name='list'),
    path('create/', views.create, name='create'),
    path('<slug:slug>/', views.answer, name='answer'),
    path('choice/<slug:slug>/', views.choice, name='choice'),
    path('edit/<slug:slug>/', views.edit, name='edit')
]

base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
ANSWER_TYPE = (
    ('text', 'text'),
    ('number', 'number'),
    ('choice', 'multiple choice')
)

class Survey(models.Model):
    name = models.CharField(max_length=200)
    question = models.TextField()
    answer_type = models.CharField(max_length=15, choices=ANSWER_TYPE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=200, unique=True)

    # a slugfield cannot have space between them rather hyphen (-)
    def get_absolute_url(self):
        return reverse('base:answer', kwargs={'slug': self.slug})

    def __str__(self):
        return self.question

class SurveyAnswer(models.Model):
    answer = models.CharField(max_length=100)
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)
    submitted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.answer[:50]

class Choice(models.Model):
    name = models.CharField(max_length=20)
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

base/forms.py
from django import forms
from .models import Survey

class SurveyForm(forms.ModelForm):
    class Meta:
        model = Survey
        fields = ['name', 'question', 'answer_type']

base/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import *
from .forms import *
# Create your views here.

def list(request):
    surveys = Survey.objects.all()

    context = {
    'surveys':surveys,
    }
    return render(request, 'list.html', context)


def create(request):
    survey_form = SurveyForm()
    user = request.user

    if request.method == 'POST':
        name = request.POST.get('name')
        question = request.POST.get('question')
        answer_type = request.POST.get('answer_type')

        survey = Survey.objects.create(
        name = name,
        question = question,
        answer_type = answer_type,
        user = user,
        slug = name.replace(" ", "-")
        )
        survey.save()

        if answer_type == 'choice':
            return redirect('base:choice', survey.slug)
        else:
            return redirect('/')

    context = {
    'survey_form':survey_form
    }
    return render(request, 'create.html', context)

def edit(request, slug):
    survey = get_object_or_404(Survey, slug=slug)
    survey_form = SurveyForm(instance=survey)
    if request.method == 'POST':
        survey_form = SurveyForm(request.POST, instance=survey)
        if survey_form.is_valid():
            survey_form.save()
            return redirect('/')

    context = {
    'survey_form':survey_form
    }
    return render(request, 'edit.html', context)

def answer(request, slug):
    survey = get_object_or_404(Survey, slug=slug)
    choices = Choice.objects.filter(survey=survey)
    print('question: ', survey.answer_type)
    print('Choice: ', choices)

    if request.method == 'POST':
        answer = request.POST.get('answer')
        print('Answer: ', type(answer))

        survey_answer = SurveyAnswer.objects.create(
        answer = answer,
        survey = survey,
        )
        survey_answer.save()
        return redirect('/')

    context = {
    'survey':survey,
    'choices':choices
    }
    return render(request, 'answer.html', context)

def choice(request, slug):
    survey = get_object_or_404(Survey, slug=slug)

    if request.method == 'POST':
        choice = request.POST.get('choice')
        new_choice = Choice.objects.create(
        name = choice,
        survey = survey
        )
        new_choice.save()
        return redirect('base:choice', slug)

    return render(request, 'choice.html')

templates/answer.html
{% extends 'main.html' %}
{% block content %}
<h1>This is the answer page</h1>
{{survey.question}}
<!-- QUESTION FORM -->
<form class="" action="" method="POST">
  {% csrf_token %}
  {% if survey.answer_type == 'choice' %}
  <select class="" name="answer">
    {% for choice in choices %}
    <option value="{{choice}}">{{choice}}</option>
    {% endfor %}
  </select>

  {% else %}
    <input type="{{survey.answer_type}}" name="answer" value="" placeholder="">
    <h2>{{survey.answer_type}}</h2>
  {% endif %}


  <input type="submit" name="" value="Submit Answer">
</form>
<!-- <input type="{{question.answer_type}}" name="" value=""> -->

{% endblock content %}

templates/choice.html
{% extends 'main.html' %}

{% block content %}
<h1>ENTER CHOICES</h1>
<form class="" action="" method="POST">
  {% csrf_token %}
  <label for="choice">Enter choice</label>
  <input type="text" name="choice" value="">
  <input type="submit" name="" value="Add Choice">
</form>

<a href="/">DONE</a>
{% endblock content %}

templates/create.html
{% extends 'main.html' %}
{% block content %}
<h1 id="create">Create Survey Page</h1>

<form class="" action="" method="POST">
  {% csrf_token %}}
  {% for field in survey_form %}
  {{field.label}}
  {{field}}
  <b></b>
  {% endfor %}
  <input type="submit" name="" value="Submit Question">
</form>
<!--
<form class="" action="" method="POST">
  {% csrf_token %}}
  <label for="name">Name</label>
  <input type="text" name="name" value="">

  <label for="question">Question</label>
  <input type="text" name="question" value="">

  <label for="answer_type">Answer Type</label>
  <select name="answer_type">
    {% for type in survey_form.answer_type %}
    <option value="{{type}}"></option>
    {% endfor %}
  </select>

  <input type="submit" name="" value="Submit Question">
</form> -->

<script>
  console.log("Jquery is working")


</script>
{% endblock content %}

templates/edit.html
{% extends 'main.html' %}
{% block content %}
<h1 id="create">Create Survey Page</h1>

<form class="" action="" method="POST">
  {% csrf_token %}}
  {% for field in survey_form %}
  {{field.label}}
  {{field}}
  <b></b>
  {% endfor %}
  <input type="hidden" name="user" value="{{request.user.id}}">
  <input type="submit" name="" value="Submit Question">
</form>

{% endblock content %}

templates/list.html
{% extends 'main.html' %}

{% block content %}
<h1>This is the survey list page</h1>
<a href="{% url 'base:create' %}">Create survey</a>

{% for survey in surveys %}
<h2>{{survey.name}}</h2>
<p>{{survey.question}}</p>
<a href="{{survey.get_absolute_url}}">Answer Question</a>
<a href="{% url 'base:edit' survey.slug %}">Edit</a>
{% endfor %}
{% endblock content %}

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Survey</title>
    <!-- JQUERY FILE -->
    <script src="{% static 'js/jquery.js' %}"></script>

  </head>
  <body>
    <a href="/">Home</a>
    {% block content %}
    {% endblock content %}


  </body>
</html>